version: "2"
services:
  app:
    container_name: app-ts
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-ts
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
